#### 创建对象
POST http://127.0.0.1:8888/simple_message/message/createObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"body":"somestring"
,"recver":"somestring"
,"sender":"somestring"
,"status":0
,"title":"somestring"
,"token":"somestring"
,"utc":0
}
 
#### 更新对象
POST http://127.0.0.1:8888/simple_message/message/updateObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"body":"somestring"
,"recver":"somestring"
,"sender":"somestring"
,"status":0
,"title":"somestring"
,"token":"somestring"
,"utc":0
}

#### 获取对象
POST http://127.0.0.1:8888/simple_message/message/getObjById
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
	"id":"somestring"
}

#### 对象列表
POST http://127.0.0.1:8888/simple_message/message/listObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json

#### 对象翻页
POST http://127.0.0.1:8888/simple_message/message/pageObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 
 "body":"somestring"
,"recver":"somestring"
,"sender":"somestring"
,"status":0
,"title":"somestring"
,"token":"somestring"
,"utc":0
}

#### 对象总数
POST http://127.0.0.1:8888/simple_message/message/count4Page
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 
 "body":"somestring"
,"recver":"somestring"
,"sender":"somestring"
,"status":0
,"title":"somestring"
,"token":"somestring"
,"utc":0
}

#### 删除对象
POST http://127.0.0.1:8888/simple_message/message/deleteObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 "id":"somestring"
}
 
#### 删除对象列表
POST http://127.0.0.1:8888/simple_message/message/deleteObjs
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
 "ids":["somestring"]
}

#### 创建对象
POST http://127.0.0.1:8888/simple_message/message/createObj
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json
 
{
"body":"somestring"
,"recver":"somestring"
,"sender":"somestring"
,"status":0
,"title":"somestring"
,"token":"somestring"
,"utc":0
}
